---
- hosts: localhost
  
  tasks:

  - name: Update APT package manager repositories cache
    ignore_errors: yes
    become: true
    apt:
      update_cache: yes
  - name: Add Docker APT repository
    become: true
    apt_repository:
      repo: deb [trusted=yes] [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install basic list of packages
    become: true
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      state: present
      update_cache: yes


  - name: Install Docker packages
    become: true
    apt:
      name: ['docker-ce','docker-ce-cli','containerd.io']
      state: present

  - name: Install Docker-compose
    become: yes
    #  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
      dest: /usr/local/bin/docker-compose
      mode: +x


